// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRsd-5dz2TlZ12cmRcoVakPZD_YDqoMsY',
    appId: '1:951964969111:web:27cc049ed58e0fa6cba1d2',
    messagingSenderId: '951964969111',
    projectId: 'geo-app-8d40e',
    authDomain: 'geo-app-8d40e.firebaseapp.com',
    storageBucket: 'geo-app-8d40e.firebasestorage.app',
    measurementId: 'G-2NEPXMKXQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP2wWnGl23aIjSHLUERuSe-crVfV2nqkk',
    appId: '1:951964969111:android:783b5f7bc134598dcba1d2',
    messagingSenderId: '951964969111',
    projectId: 'geo-app-8d40e',
    storageBucket: 'geo-app-8d40e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_xnrclm3ySQvrz7A9ni55xBZ1-3P3rD8',
    appId: '1:951964969111:ios:8aba6b88a6308f9bcba1d2',
    messagingSenderId: '951964969111',
    projectId: 'geo-app-8d40e',
    storageBucket: 'geo-app-8d40e.firebasestorage.app',
    iosBundleId: 'com.geolanka.geographyApp',
  );
}
